server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
